### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by trauchhaupt** [nativelibs4java/BridJ#99]
Are there any plans to migrate BridJ to Java 9. The code now does not work due to restrictions to load resources from other modules (e.g. Platform.getResources(String path) ).

**Comment by trauchhaupt** [comment]
My colleage found out, that the problem has nothing to do with java 9, but the way the path is constructed for the usage of system classloader ( starting with "/" will not work here ).

**Comment by msgilligan** [comment]
PR #103 seems to address this issue.

**Comment by Vampire** [comment]
Yes it does, the author of that PR **is** the mentioned colleague :-D
